### ISSUE TITLE
default country field bug

### ISSUE THREAD

**Issue by alx359** [fluidweb-co/fluid-checkout#112]
(Reported this in the [WP forums](https://wordpress.org/support/topic/default-country-field-bug/) but decided to report it here too, as it's affecting the ability to finish checkout of a certain group of customers.)

While making some tests (*), bumped into an issue when trying to enter a shipping address in a different country than the one Fluid Checkout (FC) has decided I’m located. This has proven to be a difficult to an impossible scenario, as FC is now stubbornly changing the country back in every opportunity it gets.

For example, say I’m in the US, but I’m filling a shipping address in the UK instead. After some page operation happens (ajax, reload, etc.), FC switches the country back to the US.

1) For example: https://postimg.cc/9DKRp106
2) Can’t edit an UK shipping address either, as it keeps putting it back to the US: https://postimg.cc/nXsFP8w3

The helpful workflow here would be different: FC to set the country field only if `option value=""` and do nothing otherwise.

(*) To test this, can use some VPN and fill a fluid checkout in a fresh incognito mode.

**Comment by diegoversiani** [comment]
Hi @alx359,

Thanks for reporting the issue. I'm working on it already.

I'll be closing this issue here and will reply to your ticket on the WP forums.

Best,
Diego

**Comment by diegoversiani** [comment]
For the record... this issue has been fixed as explained in the support topic:
https://wordpress.org/support/topic/default-country-field-bug/#post-15850118
