### ISSUE TITLE
Brand resources

### ISSUE THREAD

**Issue by UVLabs** [fluidweb-co/fluid-checkout#122]
I'd like to add an SVG version of your logo to my website homepage but couldn't find a suitable one on your website. Do you happen to have any?

I basically need it to be able to fit in here:

<img width="1113" alt="image" src="https://user-images.githubusercontent.com/10324144/182012391-0d6fb328-b124-4cd2-ad16-1c109f6e3018.png">

**Comment by diegoversiani** [comment]
Hi @UVLabs,

Sure. Please download it from the links below:

- Light background in color:
![logo-horizontal-dark](https://user-images.githubusercontent.com/17417563/182166584-9f2d9097-6442-4dff-8a6c-bd2fbc89779c.svg)

- Light background monochrome:
![logo-horizontal-dark-mono](https://user-images.githubusercontent.com/17417563/182166576-5ecfe2a5-e92f-40cd-b5d7-10092402bda6.svg)

If you need anything else just let me know :)

Best,
Diego
